### ISSUE TITLE
On how to reproduce C2F-TCN results

### ISSUE THREAD

**Issue by nlqd** [assembly-101/assembly101-action-recognition#2]
Hi Assembly101 team,

I'd like to ask how did you guys evaluate on action segmentation model (MS-TCN++, C2F-TCN), did you use one of the original author's checkpoints and then finetune it on Assembly101, or did you train it from scratch?

Thank you for your answer in advance. Kudos to the team btw 🎊

**Comment by assembly-101** [comment]
Hi,

Sorry for the late reply as we were finishing up on releasing the code for the temporal action segmentation task. You can now find it [here](https://github.com/assembly-101/assembly101-temporal-action-segmentation).
