### ISSUE TITLE
Will test_data_joint_200.npy or test.csv for MS-G3D be provided?

### ISSUE THREAD

**Issue by Necolizer** [assembly-101/assembly101-action-recognition#3]
Hi! Thanks for your great work. I am now trying to follow the training, validation and testing of MS-G3D, which is mentioned in [your repo](https://github.com/assembly-101/assembly101-action-recognition/tree/main/MS-G3D-action-recognition#ms-g3d-fine-grained-action-recognition-baseline-for-assembly101). Here are the problems I encounter.

1. (Solved) The npy and pkl files in [repo](https://github.com/assembly-101/assembly101-action-recognition/tree/main/MS-G3D-action-recognition/HAND_GCN/share_contex25_thresh0) are only 512kb. It seems that they're all truncated.
So I download the dataset from Google Drive and rerun the [Preprocess/1_generate_pose_data.py](https://github.com/assembly-101/assembly101-action-recognition/blob/main/MS-G3D-action-recognition/Preprocess/1_generate_pose_data.py) & [Preprocess/2_get_final_dataset.py](https://github.com/assembly-101/assembly101-action-recognition/blob/main/MS-G3D-action-recognition/Preprocess/2_get_final_dataset.py), to regenerate the data. 

2. In your guidelines, it says that

> Model parameters are set in [MS_3GD/test_config.yaml](https://github.com/assembly-101/assembly101-action-recognition/blob/main/MS-G3D-action-recognition/MS_3GD/train_config.yaml), which is currently configured to use the validation set.

So to facilitate result submission on [CodaLab Challenge](https://codalab.lisn.upsaclay.fr/competitions/5256), could test_data_joint_200.npy or test.csv for MS-G3D be provided?

3. I send the request to participate in this [challenge](https://codalab.lisn.upsaclay.fr/competitions/5256), but it seems that the decision of approval is still pending.

Thanks for your help in advance.

Best,
Necca

**Comment by assembly-101** [comment]
Hi,

2. Thanks for pointing this out. We will release it very soon.
3. You have already been accepted into the competition.

Best,
The Assembly101 Team
