### ISSUE TITLE
Evaluation Metrics for Action Recognition

### ISSUE THREAD

**Issue by Victoria-Manousaki** [assembly-101/assembly101-action-recognition#7]
Hello,

In the supplementary material in section 4.1. you state:  "We compare our “**Overall**” performance with results
obtained by **fusing scores** from _multiple views_ on recognition and anticipation in Table 7."
Could you please explain the difference in the calculation of **Overall** vs **Fusion** in Table 7?
Are both calculated for **all** views?

Best regards,
Victoria

**Comment by assembly-101** [comment]
Hi Victoria,

Thanks for your interest in our dataset.
**Overall** refers to simply increasing the test instances to `#segments X #views` i.e. treating each view as a separate instance for a segment. Whereas, **Fusion **refers to late (feature-level) fusion i.e. we average pool the TSM/TempAgg features (2048-D/512-D) from all the views for one segment thus having one output and hence one prediction for each segment.

Both **Overall** and **Fusion** are calculated for all views available for a segment.
I hope this answers your question.

Best,
Assembly101 Team

**Comment by Victoria-Manousaki** [comment]
Yes, this answers my question. Thank you!

The pretrained models that you provide correspond to the **Overall** or **Fusion** ?

**Comment by assembly-101** [comment]
The pretrained models provided have been trained on all training `#segments X #views`. We differentiate **overall** vs **fusion** per segment only during evaluation.

**Comment by Victoria-Manousaki** [comment]
Thank you very much for your time!
